burnout: /burnout
support_group: https://
open_source: https://medium.com/@jlondiche/jarr%C3%AAte-le-recrutement-propri%C3%A9taire-je-d%C3%A9marre-l-open-source-6e33463aec9
job_board: https://github.com/jlondiche/job-board-php
linkedin: https://www.linkedin.com/in/jlondiche
