burnout: /burnout
open_source: https://medium.com/@jlondiche/jarr%C3%AAte-le-recrutement-propri%C3%A9taire-je-d%C3%A9marre-l-open-source-6e33463aec9
job_board: https://github.com/jlondiche/job-board-php
linkedin: https://www.linkedin.com/in/jlondiche
slack: https://jlrecrutement.slack.com/join/shared_invite/zt-ixbnavub-1xvzULppv6SomrOIW50h1g#/
